title: Gaurav Singh Lab @ SNIoE
short_title: Gaurav Singh Lab
subtitle: Shiv Nadar Institution of Eminence (SNIoE)
description: Research group website for organelle biology, biosensors, and quantitative biology.
tagline: Organelle Biology
url: "https://gauravsinghlab.github.io"
baseurl: ""

email: gaurav.singh@snu.edu.in
orcid_url: https://orcid.org/0000-0001-8514-0739
scholar_url: https://scholar.google.co.in/citations?user=iq-O6EwAAAAJ&hl=en

nav:
  - title: Home
    url: /
  - title: Research
    url: /research/
  - title: Members
    url: /members/
  - title: Publications
    url: /publications/
  - title: News
    url: /news/
  - title: Gallery
    url: /gallery/
  - title: Contact
    url: /contact/

permalink: pretty
timezone: Asia/Kolkata

plugins:
  - jekyll-feed

exclude:
  - README.md
